"""Add trigram search

Revision ID: 22ad61d04014
Revises: ceb7976848af
Create Date: 2025-07-06 11:39:43.624010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ad61d04014'
down_revision: Union[str, Sequence[str], None] = 'ceb7976848af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')
    op.create_index('ix_application_name_trgm', 'applications', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('ix_manufacturer_name_trgm', 'manufacturers', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_manufacturer_name_trgm', table_name='manufacturers', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_application_name_trgm', table_name='applications', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.execute('DROP EXTENSION IF EXISTS pg_trgm;')
    # ### end Alembic commands ###
