"""Add user expire

Revision ID: 3792d91a7dbc
Revises: 22ad61d04014
Create Date: 2025-07-10 11:42:20.998973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3792d91a7dbc'
down_revision: Union[str, Sequence[str], None] = '22ad61d04014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_invites', sa.Column('duration_month', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('expire', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'expire')
    op.drop_column('auth_invites', 'duration_month')
    # ### end Alembic commands ###
