"""Add application area

Revision ID: 3c2fd001584a
Revises: 72591089d18b
Create Date: 2025-07-17 06:44:21.389738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c2fd001584a'
down_revision: Union[str, Sequence[str], None] = '72591089d18b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_area_entry',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['area_id'], ['application_area.id'], ),
    sa.PrimaryKeyConstraint('application_id', 'area_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_area_entry')
    op.drop_table('application_area')
    # ### end Alembic commands ###
