"""Add language model to application

Revision ID: b05314ff439a
Revises: f0c7a06ad151
Create Date: 2025-06-22 15:18:50.391834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b05314ff439a'
down_revision: Union[str, Sequence[str], None] = 'f0c7a06ad151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_models_id'), 'language_models', ['id'], unique=False)
    op.create_table('model_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_choices_id'), 'model_choices', ['id'], unique=False)
    op.add_column('applications', sa.Column('languagemodel_id', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('modelchoice_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'applications', 'model_choices', ['modelchoice_id'], ['id'])
    op.create_foreign_key(None, 'applications', 'language_models', ['languagemodel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'modelchoice_id')
    op.drop_column('applications', 'languagemodel_id')
    op.drop_index(op.f('ix_model_choices_id'), table_name='model_choices')
    op.drop_table('model_choices')
    op.drop_index(op.f('ix_language_models_id'), table_name='language_models')
    op.drop_table('language_models')
    # ### end Alembic commands ###
