"""Add table risks

Revision ID: ceb7976848af
Revises: 09a46b08e2a5
Create Date: 2025-07-04 11:25:16.475850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb7976848af'
down_revision: Union[str, Sequence[str], None] = '09a46b08e2a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_id'), 'risk', ['id'], unique=False)
    op.add_column('application_users', sa.Column('risk_id', sa.Integer(), nullable=True))
    op.create_foreign_key('application_users_risk_id_fkey', 'application_users', 'risk', ['risk_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('application_users_risk_id_fkey', 'application_users', type_='foreignkey')
    op.drop_column('application_users', 'risk_id')
    op.drop_index(op.f('ix_risk_id'), table_name='risk')
    op.drop_table('risk')
    # ### end Alembic commands ###
